### ISSUE TITLE
data value not equal

### ISSUE THREAD

**Issue by guba91** [mhzawadi/foxess-mqtt#11]
Hi,
i keep seeing a difference with what this project read and publish in mqtt and what i have on the foxess webpage.
as per example:
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/96147a86-0c00-44df-8ac4-294300e5edc1)
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/ef4ec7b5-e3ce-4bfd-a7ca-92b840321cd5)

**Comment by mhzawadi** [comment]
Hi @guba91 

I too have differences in the data, Im not sure if the data should be rounded up or down when trimming the decimal points. any thoughts?

**Comment by guba91** [comment]
> Hi @guba91 
> 
> I too have differences in the data, Im not sure if the data should be rounded up or down when trimming the decimal points. any thoughts?

Is possible to publish in another mqtt topic some debug data? Like raw value

**Comment by mhzawadi** [comment]
the directory where the foxess data is stored is a file called `collected.json` that has the raw data from the foxess site

**Comment by mhzawadi** [comment]
Hello @guba91 

I have a new dev image that now rounds up the data rather then down, it needs some testing before I merge to main.

if you want to test, image to pull is dev-php - docker pull mhzawadi/foxess-mqtt:dev-php

**Comment by guba91** [comment]
Thanks @mhzawadi!
pull and running, tomorrow we will see how it's going!
:)

**Comment by mhzawadi** [comment]
I have good news and bad, I have found that each device reports day and all time totals for generation
```
"generationToday": "1.900",
"generationTotal": "4801.100",
```

So I now use the generationTotal for the `generationPower_kwh` value, the bad news is that will mes up your data for a bit

**Comment by mhzawadi** [comment]
well the current dev image is working
HA - 
![image](https://github.com/mhzawadi/foxess-mqtt/assets/11944327/562bd21f-f2ba-417b-9bfc-9e7e80463680)

FoxEss cloud -
![image](https://github.com/mhzawadi/foxess-mqtt/assets/11944327/bd97d88d-7601-41ec-97ec-c1ff83029b4c)

**Comment by guba91** [comment]
yeah, i need to update the mqtt configuration in home assistant because now the topic is foxesscloud/SERIALNR/#
lol 🤣 
thats why it wasnt working :D 🤣

**Comment by mhzawadi** [comment]
yeah, I had the same thing. sorry

**Comment by guba91** [comment]
no problem 😆 
look like it's working!
thanks!
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/b14dcfff-f4ec-40d0-bae4-6e14ae46ac34)

**Comment by guba91** [comment]
do you know where i'm wrong here?
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/3cc239ff-a38b-459d-8158-080f744947fb)
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/27488296-f98f-4f4d-9397-0c1abdcf1836)

**Comment by mhzawadi** [comment]
oh I may have forgot to say, you dont need to add an mqtt sensor as this will add auto config topics that home assistant should see. in your MQTT integration should be the device for your inverter, complete with a load of senors

**Comment by guba91** [comment]
yeee.. nope.. it worked for a while, don't know if is something in my config somewhere
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/d43cad8c-07bb-4707-81f5-fc12ae76c7eb)

**Comment by mhzawadi** [comment]
how odd, could check with an mqtt client that you get the updates?

**Comment by guba91** [comment]
let me check :)
sorry i'm at work and doing multiple things at once 🤣

**Comment by mhzawadi** [comment]
the container should have logs of what its doing, also set `"log_level": 3`

**Comment by guba91** [comment]
now seems fine, but soc is in kW instead of % 🤣 
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/d2146a18-88b7-438a-9657-50306dc10724)

**Comment by mhzawadi** [comment]
both good news and a 🤦🏼 
will have a look and fix this evening, thanks.

please close this if your all sorted

**Comment by guba91** [comment]
data is still off, a lot on soc, i've enabled log3 and moved collected.json, restarted container and soc is still at 46, from app soc is at 94 at the moment.. i'll try to take a deeper look but i'm a bit busy, hope to do it today

**Comment by mhzawadi** [comment]
thanks so much for your help, the big issue is I dont have any batteries so my SoC is 0, also note that the data you see form this and the date on the app/site could be 3+ minutes out

**Comment by guba91** [comment]
Thanks to you for everything!!

yeah that's a problem because for soc, i need to look at the data while the battery is chargin (in the morning) or discharding after sunset, so... yeah 🤣

**Comment by guba91** [comment]
foxesscloud/6---/SoC 69
it's NICE but wrong LOL should be 94 🤣

**Comment by guba91** [comment]
can it be off becuase of the time zone?
did the data pulled with some kind of timestamps?
from the logs: 2023-07-12 11:01:55 - Post 69 of SoC to MQTT
at 12.00 italy time (so an hour ago) it was 69%

**Comment by guba91** [comment]
in the collected, it stores the info of 2 hours ago 
        "36": {
            "variable": "RPower",
            "unit": "kW",
            "name": "RPower",
            "data": {
                "0": {
                    "time": "2023-07-12 11:04:04 CEST+0200",
                    "value": 0.346
                },
                "1": {
                    "time": "2023-07-12 11:09:04 CEST+0200",
                    "value": 0.357
                },
                "2": {
                    "time": "2023-07-12 11:14:04 CEST+0200",
                    "value": 0.355
                },
                "3": {
                    "time": "2023-07-12 11:19:04 CEST+0200",
                    "value": 0.351
                },
                "4": {
                    "time": "2023-07-12 11:24:04 CEST+0200",
                    "value": 0.257
                },
                "5": {
                    "time": "2023-07-12 11:29:04 CEST+0200",
                    "value": 0.329
                },
                "6": {
                    "time": "2023-07-12 11:34:04 CEST+0200",
                    "value": 0.367
                },
                "7": {
                    "time": "2023-07-12 11:39:04 CEST+0200",
                    "value": 0.31
                },
                "8": {
                    "time": "2023-07-12 11:44:04 CEST+0200",
                },
                "9": {
                    "time": "2023-07-12 11:49:04 CEST+0200",
                    "value": 0.328
                },
                "10": {
                    "time": "2023-07-12 11:54:05 CEST+0200",
                    "value": 0.312
                },
                "11": {
                    "time": "2023-07-12 11:59:04 CEST+0200",
                    "value": 0.333
                }
            }

**Comment by mhzawadi** [comment]
can you post your compose or run command please?
PHP should have your time zone

**Comment by mhzawadi** [comment]
also have added a fix for the SoC and a log line for the timezone to PHP in the dev image, if PHP shows the right timezone then I need to check how I make date

**Comment by guba91** [comment]
2023-07-12 12:52:40 - Post 96 of SoC to MQTT
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/4efac0a4-0c9b-490a-ae8e-7029f291becc)
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/e1f364b8-2ce5-485a-ac19-c8d069541ffe)

[logs.txt](https://github.com/mhzawadi/foxess-mqtt/files/12028172/logs.txt)

seems like something is wrong with the time, but i'm a little confused on how it's wrong 🤣

**Comment by mhzawadi** [comment]
found your problem, this `-e -TIMEZONE=Europe/Rome` should be `-e TIMEZONE=Europe/Rome`. The `-` is not needed when you run from the terminal like that.

Also `We dont have a timezone, it could UTC` is the line I was looking for

**Comment by guba91** [comment]
omg -.-

**Comment by guba91** [comment]
**can't belive it, how i don't see that!!**
ok so when you merge to main the dev-php?
can i help you with something else in this project?

**Comment by mhzawadi** [comment]
I have updated the readme and the docker hub page, I hope that will stop others with the same issue.

All the changes you need are now in main and tagged as v0.0.4, the dev image will now get the next set of changes.

if you have more things, please open a new issue for them, I can then track each new big change

**Comment by guba91** [comment]
ok, so i'll keep updating the dev-php to test new feature and give feedback!
thanks a lot!
PS: pm on reddit
