### ISSUE TITLE
More than 1 inverter

### ISSUE THREAD

**Issue by GCtrl** [mhzawadi/foxess-mqtt#12]
Hey,

Thanks for your work, i like it.
Could you please insert that the mqtt-topic is perhaps the device-id and not generic "foxesscloud"?
That could be helpful, if someone has more than one inverter.

Greetings

**Comment by mhzawadi** [comment]
Hello @GCtrl 

do you have more than 1 inverter? could I get a screen shot of this page - https://www.foxesscloud.com/bus/device/inverter (minus any personal data)

it looks like I would need to query for all inverters and then store data for each, a but of work for sure

**Comment by GCtrl** [comment]
Hello,
yes, I have 2 of them, here's the screenshot.

![image](https://github.com/mhzawadi/foxess-mqtt/assets/138067310/d6060e60-5e3a-4e5f-95f4-dc766c18e1de)

Thank you :-)

**Comment by mhzawadi** [comment]
thats great, will see what I can do

**Comment by mhzawadi** [comment]
thats a far bigger job than it looks, will try and keep you posted on progress

**Comment by mhzawadi** [comment]
Hello @GCtrl 

I have a new dev image with multi inverter support, please can you test it and let me know what I broke in the process.

image to pull is dev-php - `docker pull mhzawadi/foxess-mqtt:dev-php`

**Comment by GCtrl** [comment]
Hi @mhzawadi.

it seems like it is working. I filled out the "device-ID" in the config.json, but it has no impact any longer or? (because you're grabbing the device IDs of any device which is listed).

Foxcloud is updating every 5 minutes, right?
Perhaps you could decrease the sleep time of run.sh a bit:
If the server update would be a bit late and the sleep time of 5 minutes runs out after that moment, then it could happen that the mqtt-update doesn't change for nearly 10 minutes or?
I put myself the sleep time to 3 minutes.

Thank you very much until that.

**Comment by mhzawadi** [comment]
thats all good news, the update timeout is an issue Im not sure how to fix.

If you look at the collected.json file you can see how often your inverters check in, its anywhere from 3 minutes up. I can edit down and see how that goes, will have a look this evening

**Comment by mhzawadi** [comment]
have made the 3 minute change and new image is ready for testing, Im about to use it now. Wish me luck

**Comment by mhzawadi** [comment]
have sorted out all the home assistant stuff and working sweet for me

**Comment by mhzawadi** [comment]
new image, I am now using the `generationTotal` of the device for the `generationPower_kwh` value. this will mess up your data for a day or so

**Comment by mhzawadi** [comment]
going to merge the dev image as it looks like I have sorted this

**Comment by mhzawadi** [comment]
closing as no reported issues, please reopen if you need help
