### ISSUE TITLE
inverterid_soc in kW not %

### ISSUE THREAD

**Issue by guba91** [mhzawadi/foxess-mqtt#15]
Hi,
the value _soc is correct but is in kW, not sure if it's my homeassistant because of older version of foxess-mqtt with wrong value or wrong unit still in production

**Comment by mhzawadi** [comment]
thats not how this works, will have a look

**Comment by mhzawadi** [comment]
the dev image should have a fix in it, will have a look and if all good merge in main

**Comment by guba91** [comment]
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/69f84181-d814-49e8-ad9b-2b09b20265cc)
what 🤣 🤣 🤣 
percentage is now correct but ca i suggest a change in the icon? 🤣  something like mdi:home-battery-outline

**Comment by mhzawadi** [comment]
will have a look at what I can do, but Im not sure I have control over the image

**Comment by guba91** [comment]
ohh i see.. maybe it have something to do with the type or something.. i don't know
