### ISSUE TITLE
Password changed to md5?

### ISSUE THREAD

**Issue by comfreak89** [mhzawadi/foxess-mqtt#2]

**Comment by comfreak89** [comment]
The transmitted password is now in md5 encoded. Plaintext does not work anymore.

Also username and password is mixed up in "foxess-login.sh"

`-d "{
    \"user\": \"${FOXESS_PASSWORD}\",
    \"password\": \"${FOXESS_USERNAME}\"`

**Comment by mhzawadi** [comment]
Thanks for pointing out the vars are wrong, I have also checked the login flow and I can still see my password in plain text.

If you have seen yours MD5ed, could you point me at the URL please?

**Comment by mhzawadi** [comment]
also new image should have built and be on the docker hub for you to test

**Comment by comfreak89** [comment]
I do not have the issue - my colleage has and I just wanted to point out, that he has to authenticate with an hased md5 password.

The script did not work with the plain text password. After we decrypted the https traffic together from the website via wireshark (decoded TLS with Chrome) there saw that a JavaScript hashes the password with md5 locally before transmitting via https to their servers. After we hashed the password with md5, the script worked.

**Comment by mhzawadi** [comment]
So I have been working on a PHP version of this and I still have it working fine with MD5 hashing the password, could you try the dev build on the docker hub?

**Comment by mhzawadi** [comment]
yep, thats a thing I have just spotted 🤦🏼 

I have a new PHP thing that should now work, your colleague will need to make some changes to get the new program to work

**Comment by mhzawadi** [comment]
closing, new PHP re-write has fixed
