### ISSUE TITLE
how reset kwh value every day

### ISSUE THREAD

**Issue by guba91** [mhzawadi/foxess-mqtt#22]
feedinpower_kwh, _gridconsumptionpower_kwh, _pv1power_kwh show absolute value from when i've added to homeassistant, how to make it reset every night? 
so the value will be "daily grid consumption" and so on?
Thanks :)

**Comment by mhzawadi** [comment]
Hey @guba91 

Whats the need to reset them? 

You can add feedin and gridconsumption to the energy dashboard and that will track daily usage, like the below.

![image](https://github.com/mhzawadi/foxess-mqtt/assets/11944327/1a8ce4ad-aa7f-465a-bdb3-fc0088be810a)
![Screenshot 2023-09-20 at 21 08 52](https://github.com/mhzawadi/foxess-mqtt/assets/11944327/38da5c9e-f3d7-4ec6-a48e-a708d3e20f64)

**Comment by guba91** [comment]
because why not :)
the sensor _kwh is meant to be a daily total i think, maybe i'm wrong.

**Comment by mhzawadi** [comment]
So I have had a think and getting a sensor to do that is a bit complex, but home assistant has you covered. The Utility meter is what your looking for, see if that helps.

https://www.home-assistant.io/integrations/utility_meter/

**Comment by guba91** [comment]
i'm looking at 
https://github.com/macxq/foxess-ha/blob/559a54e7ee3a2aaa47b6eadb76ba7bdaae7af623/custom_components/foxess/sensor.py#L1260C68-L1260C68
 because even if i don't like to have the integration doing all the work in this way, the sensor is working correctly resetting day by day, but i'm not able to understand how your code works hahahaha

**Comment by mhzawadi** [comment]
will have a look and see what I can do, I think its the type of sensor I use that resets

**Comment by mhzawadi** [comment]
Good news, I have added code to allow tracking total over time or just use the data at every run.
The dev image should have the code in it, please add `"total_over_time": false` to your config and see if you get `total over time is: false` in the logs

**Comment by mhzawadi** [comment]
v0.0.7 is out, please test it
