### ISSUE TITLE
reading zero every hour

### ISSUE THREAD

**Issue by guba91** [mhzawadi/foxess-mqtt#25]
Hi, it's only mine installation that every hour goes brrrr?

![Screenshot 2023-09-27 090623](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/ac6f6612-da91-444a-9c02-74aaa4a817b5)
![Screenshot 2023-09-27 102025](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/7e2c49d3-2167-463d-8c9e-84e56a4d8611)
![Screenshot 2023-09-27 102103](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/bfe91aee-50cf-4b36-8b32-e91a51f05fef)
![Screenshot 2023-09-27 102030](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/fb44aa2e-ed30-4f29-a1ea-1bb24935f5ea)
![Screenshot 2023-09-27 102038](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/ae69c217-e71d-49c5-84de-e502e2184afd)
![Screenshot 2023-09-27 102042](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/1adaa0eb-486a-491f-8f1a-1405883b1564)
![Screenshot 2023-09-27 102047](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/dd32959f-a204-48ce-9028-63074ee058b0)
![Screenshot 2023-09-27 102051](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/89550c00-c411-486d-bd2e-71c7664bc544)
![Screenshot 2023-09-27 102055](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/b9a7e9e6-6bf9-450a-82bf-2ad879a1ae78)

**Comment by mhzawadi** [comment]
no, I get the same thing. not sure how I make the data less pants

**Comment by mhzawadi** [comment]
This may get fixed with the new openAPI in v0.1.0, if you still get odd drops I can have a look

**Comment by mhzawadi** [comment]
new openAPI code has been merged #30 

Please close this if that sorted your issue, it has for me
![image](https://github.com/mhzawadi/foxess-mqtt/assets/11944327/2cc73f46-50d6-459f-9f63-000986b8be9a)

**Comment by guba91** [comment]
let me update and see :) thanks

**Comment by guba91** [comment]
looks ok to me <3
