### ISSUE TITLE
Foxess changed api

### ISSUE THREAD

**Issue by guba91** [mhzawadi/foxess-mqtt#29]
https://github.com/macxq/foxess-ha/issues/206

**Comment by guba91** [comment]
::sad

**Comment by mhzawadi** [comment]
crap, I still dont line this wank inverter and the shitty cloud thing.

Thanks @guba91 for the heads up

**Comment by Golempl** [comment]
20 api hits per day, thats ridiculous.

**Comment by guba91** [comment]
i'm going with the modbus integration, was planning to do that for a while, now it's time..
https://github.com/nathanmarlor/foxess_modbus
with this adapter https://github.com/nathanmarlor/foxess_modbus/wiki/Waveshare-RS485-to-ETH-%28B%29

**Comment by mhzawadi** [comment]
PHP fix maybe?

```
echo md5(utf8_encode('/c/v0/user/login\r\n\r\nen\r\n1703163390258'));
echo md5(utf8_encode('PATH\r\nTOKEN\r\nLANG\r\nTIMESTAMP'));
```

also
```
    headers['Token'] = token
    headers['Lang'] = lang
    headers['User-Agent'] = token_store['user_agent']
    headers['Timezone'] = token_store['time_zone']
    headers['Timestamp'] = timestamp
    headers['Content-Type'] = 'application/json;charset=UTF-8'
    headers['Signature'] = hashlib.md5(fr"{path}\r\n{headers['Token']}\r\n{headers['Lang']}\r\n{headers['Timestamp']}".encode('UTF-8')).hexdigest() + '.5245784'
```

**Comment by mhzawadi** [comment]
I now need to start the move to the new API, but the old method is now active again.

Once the new API has been adopted by all integrations the old method will get removed, will keep this updated as much as I can

**Comment by guba91** [comment]
If you need a tester ask me :) no problem at all

**Comment by mhzawadi** [comment]
great, that might help. Do you have multiple inverters?

**Comment by hansjoerg-jahnke** [comment]
If you need another tester, i´m here ;-)

**Comment by mhzawadi** [comment]
Hey @hansjoerg-jahnke & @guba91 

Thanks for the offer, I have a 0.1.0 image that might work with the new API. Its still very much a work in progress, but if your up for some testing that would be good.

You will need to login to the FoxESS portal and make an API key, make sure to store that somewhere safe (like a password manager).

`docker pull mhzawadi/foxess-mqtt:dev-php-0.1.0` to pull the image

You will then need to update your config.json with the below, then run the image and see if you get any data back

```
"foxess_apikey": "changeme",
"foxess_lang": "en",
```

I may have hit some kind of rate limit this evening, so will need to come back and fix any issues that crop up

**Comment by guba91** [comment]
Hi!
PHP Warning:  Undefined array key "foxess_apikey" in /foxess-mqtt/src/model/config.php on line 30
in the logs is ok? =P

**Comment by guba91** [comment]
`Setting your timezone to Europe/Rome
We have all the files we need
first run will sleep for 3 seconds to allow MQTT to get setup
This is our timezone: Europe/Rome
PHP Warning:  Undefined array key "foxess_apikey" in /foxess-mqtt/src/model/config.php on line 30
2024-01-19 00:09:48 [INFO] Collect data from the cloud
Setting your timezone to Europe/Rome
We have all the files we need
first run will sleep for 3 seconds to allow MQTT to get setup
This is our timezone: Europe/Rome
2024-01-19 00:11:24 [INFO] Collect data from the cloud
2024-01-19 00:12:32 [INFO] Data collected
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function MHorwood\foxess_mqtt\model\mqtt::__construct(), 0 passed in /foxess-mqtt/src/model/data.php on line 61 and exactly 1 expected in /foxess-mqtt/src/model/mqtt.php:11
Stack trace:
#0 /foxess-mqtt/src/model/data.php(61): MHorwood\foxess_mqtt\model\mqtt->__construct()
#1 /foxess-mqtt/src/controller/foxess_data.php(59): MHorwood\foxess_mqtt\model\data->process_data()
#2 /foxess-mqtt/run.php(8): MHorwood\foxess_mqtt\controller\foxess_data->__construct()
#3 {main}
  thrown in /foxess-mqtt/src/model/mqtt.php on line 11
This is our timezone: Europe/Rome
2024-01-19 00:14:09 [INFO] Collect data from the cloud
2024-01-19 00:14:10 [INFO] Data collected
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function MHorwood\foxess_mqtt\model\mqtt::__construct(), 0 passed in /foxess-mqtt/src/model/data.php on line 61 and exactly 1 expected in /foxess-mqtt/src/model/mqtt.php:11
Stack trace:
#0 /foxess-mqtt/src/model/data.php(61): MHorwood\foxess_mqtt\model\mqtt->__construct()
#1 /foxess-mqtt/src/controller/foxess_data.php(59): MHorwood\foxess_mqtt\model\data->process_data()
#2 /foxess-mqtt/run.php(8): MHorwood\foxess_mqtt\controller\foxess_data->__construct()
#3 {main}
  thrown in /foxess-mqtt/src/model/mqtt.php on line 11
This is our timezone: Europe/Rome
2024-01-19 00:15:11 [INFO] Collect data from the cloud
`
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/03244a43-1c2d-4588-ad18-d70068cd63da)

**Comment by mhzawadi** [comment]
Hey @guba91 

Did you update your `config.json` with new options?
Make sure to put your real key in

```
"foxess_apikey": "changeme",
"foxess_lang": "en",
```

**Comment by guba91** [comment]
i'm dumb but not that much :)
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/8837100b-637b-4a2b-bc58-ff041887aab3)

**Comment by mhzawadi** [comment]
pants, needs more work then 😞

**Comment by hansjoerg-jahnke** [comment]
Unfortunately, I am not receiving any data.


PHP Warning:  Trying to access array offset on value of type null in /foxess-mqtt/src/controller/foxess_data.php on line 45

2024-01-19 15:49:33 [INFO] Update MQTT and device list

2024-01-19 15:49:33 [INFO] start of device listing

2024-01-19 15:51:47 [ERROR] Empty device list

2024-01-19 15:51:47 [ERROR] Issues getting devices

PHP Warning:  Trying to access array offset on value of type null in /foxess-mqtt/src/controller/foxess_data.php on line 55

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function MHorwood\foxess_mqtt\model\mqtt::__construct(), 0 passed in /foxess-mqtt/src/model/data.php on line 61 and exactly 1 expected in /foxess-mqtt/src/model/mqtt.php:11

Stack trace:

#0 /foxess-mqtt/src/model/data.php(61): MHorwood\foxess_mqtt\model\mqtt->__construct()

#1 /foxess-mqtt/src/controller/foxess_data.php(59): MHorwood\foxess_mqtt\model\data->process_data()

#2 /foxess-mqtt/run.php(8): MHorwood\foxess_mqtt\controller\foxess_data->__construct()

#3 {main}

  thrown in /foxess-mqtt/src/model/mqtt.php on line 11

**Comment by hansjoerg-jahnke** [comment]
But the counter in "API Management" counts downwards.

**Comment by mhzawadi** [comment]
Hi all,

I have been working on this to and now have a working image, there is a big change in the new image!!

**Comment by mhzawadi** [comment]
After a bit of a tidy up, I now have the class of sensor working. As well as the total_increasing for the `todayYield` var.

new image pushed and ready for more testing, I have it running and connected to my HA. So will repot how I get on tomorrow

**Comment by hansjoerg-jahnke** [comment]
Still this image?

mhzawadi/foxess-mqtt:dev-php-0.1.0

**Comment by guba91** [comment]
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/381bffb6-e107-4fb8-95d1-ffcad5cc1b18)
working!!

**Comment by guba91** [comment]
oh boy, if you have multiple inverter, it read both
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/7b312c60-c4e9-462c-89df-db0cea5e8993)

**Comment by hansjoerg-jahnke** [comment]
Your work is incredible. The data is pulled from the cloud and transferred to my mqtt-broker without any problems. The sensors are recognized immediately in Homeassistant.

**Comment by hansjoerg-jahnke** [comment]
Still some warnings and one error. The updating of the data will not be continued.


thrown in /foxess-mqtt/src/model/data.php on line 68

This is our timezone: Europe/London

PHP Warning:  Undefined variable $isok in /foxess-mqtt/src/model/request.php on line 103

PHP Warning:  Trying to access array offset on value of type bool in /foxess-mqtt/src/model/data.php on line 68

PHP Warning:  Trying to access array offset on value of type null in /foxess-mqtt/src/model/data.php on line 68

PHP Warning:  Trying to access array offset on value of type null in /foxess-mqtt/src/model/data.php on line 68

PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /foxess-mqtt/src/model/data.php:68

Stack trace:
#0 /foxess-mqtt/src/model/data.php(68): count()
#1 /foxess-mqtt/src/controller/foxess_data.php(58): MHorwood\foxess_mqtt\model\data->process_data()
#2 /foxess-mqtt/run.php(8): MHorwood\foxess_mqtt\controller\foxess_data->__construct()

}
  thrown in /foxess-mqtt/src/model/data.php on line 68
2024-01-20 22:20:15 [ERROR] Issue getting error codes

**Comment by mhzawadi** [comment]
Thanks for your testing @hansjoerg-jahnke , will have a look at the errors. That could be you coundn't get any data, but will see where it failed

**Comment by mhzawadi** [comment]
I have pushed a new image tagged 0.1.0, this I hope will flag up that the cloud failed to send data.
Also new sensors for feedin KWh and Grid consumption KWh

**Comment by hansjoerg-jahnke** [comment]
No errors for the moment. So far, the minute by minute update of the data is running smoothly.

**Comment by mhzawadi** [comment]
Evening all,

If I dont see any more issues this week, I will push this to master on Wednesday. before I do that, could I get some feedback on the readme?

 https://github.com/mhzawadi/foxess-mqtt/blob/0.1.0/README.md

**Comment by hansjoerg-jahnke** [comment]
I have no comments on the readme. It looks good to me. No other errors have occurred so far.

**Comment by mhzawadi** [comment]
Thats it, its now live.

#30 merged to main and latest docker hub image is up, if you get any issues from here on out please open a new issue.
