### ISSUE TITLE
some error on first run 

### ISSUE THREAD

**Issue by guba91** [mhzawadi/foxess-mqtt#3]
First time using this docker image, this is the output.. :( 

> latest: Pulling from mhzawadi/foxess-mqtt
> 2ff1d7c41c74: Pull complete 
> ff448f5b705d: Pull complete 
> 0153262e65e7: Pull complete 
> 4f4fb700ef54: Pull complete 
> Digest: sha256:8865f4ca576f9de96846629c6a0c6f2f9bbe7e43e7849cca14ccefc4e51db166
> Status: Downloaded newer image for mhzawadi/foxess-mqtt:latest
> jq - commandline JSON processor [version 1.5-1-a5b5cbe]
> Usage: jq [options] <jq filter> [file...]
> 
> 	jq is a tool for processing JSON inputs, applying the
> 	given filter to its JSON text inputs and producing the
> 	filter's results as JSON on standard output.
> 	The simplest filter is ., which is the identity filter,
> 	copying jq's input to its output unmodified (except for
> 	formatting).
> 	For more advanced filters see the jq(1) manpage ("man jq")
> 	and/or https://stedolan.github.io/jq
> 
> 	Some of the options include:
> 	 -c		compact instead of pretty-printed output;
> 	 -n		use `null` as the single input value;
> 	 -e		set the exit status code based on the output;
> 	 -s		read (slurp) all inputs into an array; apply filter to it;
> 	 -r		output raw strings, not JSON texts;
> 	 -R		read raw strings, not JSON texts;
> 	 -C		colorize JSON;
> 	 -M		monochrome (don't colorize JSON);
> 	 -S		sort keys of objects on output;
> 	 --tab	use tabs for indentation;
> 	 --arg a v	set variable $a to value <v>;
> 	 --argjson a v	set variable $a to JSON value <v>;
> 	 --slurpfile a f	set variable $a to an array of JSON texts read from <f>;
> 	See the manpage for more options.
> cat: .token: No such file or directory
> (23) Failed writing body
> ./foxess-data.sh: line 41: [: -eq: unary operator expected
> ./foxess-data.sh: line 45: [: -gt: unary operator expected

**Comment by guba91** [comment]
also tried with the php-dev version and this is the output:


root@manage:~# docker run --name foxescloud   -e -TIMEZONE=Europe/Rome   -v /root/foxess-mqtt:/foxess-mqtt/data   mhzawadi/foxess-mqtt
cat: .token: No such file or directory
jq - commandline JSON processor [version 1.5-1-a5b5cbe]
Usage: jq [options] <jq filter> [file...]

	jq is a tool for processing JSON inputs, applying the
	given filter to its JSON text inputs and producing the
	filter's results as JSON on standard output.
	The simplest filter is ., which is the identity filter,
	copying jq's input to its output unmodified (except for
	formatting).
	For more advanced filters see the jq(1) manpage ("man jq")
	and/or https://stedolan.github.io/jq

	Some of the options include:
	 -c		compact instead of pretty-printed output;
	 -n		use `null` as the single input value;
	 -e		set the exit status code based on the output;
	 -s		read (slurp) all inputs into an array; apply filter to it;
	 -r		output raw strings, not JSON texts;
	 -R		read raw strings, not JSON texts;
	 -C		colorize JSON;
	 -M		monochrome (don't colorize JSON);
	 -S		sort keys of objects on output;
	 --tab	use tabs for indentation;
	 --arg a v	set variable $a to value <v>;
	 --argjson a v	set variable $a to JSON value <v>;
	 --slurpfile a f	set variable $a to an array of JSON texts read from <f>;
	See the manpage for more options.
(23) Failed writing body
./foxess-data.sh: line 41: [: -eq: unary operator expected
./foxess-data.sh: line 45: [: -gt: unary operator expected
usage: mqttools publish [-h] [--host HOST] [--port PORT]
                        [--client-id CLIENT_ID] [--count COUNT] [--size SIZE]
                        [--retain] [--will-topic WILL_TOPIC]
                        [--will-message WILL_MESSAGE] [--will-retain]
                        [--response-topic RESPONSE_TOPIC]
                        [--username USERNAME] [--password PASSWORD]
                        [--session-expiry-interval SESSION_EXPIRY_INTERVAL]
                        [--message-format {auto,binary,text}]
                        [--cafile CAFILE] [--no-check-hostname]
                        topic [message]
mqttools publish: error: argument --host: expected one argument
usage: mqttools publish [-h] [--host HOST] [--port PORT]
                        [--client-id CLIENT_ID] [--count COUNT] [--size SIZE]
                        [--retain] [--will-topic WILL_TOPIC]
                        [--will-message WILL_MESSAGE] [--will-retain]
                        [--response-topic RESPONSE_TOPIC]
                        [--username USERNAME] [--password PASSWORD]
                        [--session-expiry-interval SESSION_EXPIRY_INTERVAL]
                        [--message-format {auto,binary,text}]
                        [--cafile CAFILE] [--no-check-hostname]
                        topic [message]
mqttools publish: error: argument --host: expected one argument
usage: mqttools publish [-h] [--host HOST] [--port PORT]
                        [--client-id CLIENT_ID] [--count COUNT] [--size SIZE]
                        [--retain] [--will-topic WILL_TOPIC]
                        [--will-message WILL_MESSAGE] [--will-retain]
                        [--response-topic RESPONSE_TOPIC]
                        [--username USERNAME] [--password PASSWORD]
                        [--session-expiry-interval SESSION_EXPIRY_INTERVAL]
                        [--message-format {auto,binary,text}]
                        [--cafile CAFILE] [--no-check-hostname]
                        topic [message]
mqttools publish: error: argument --host: expected one argument
usage: mqttools publish [-h] [--host HOST] [--port PORT]
                        [--client-id CLIENT_ID] [--count COUNT] [--size SIZE]
                        [--retain] [--will-topic WILL_TOPIC]
                        [--will-message WILL_MESSAGE] [--will-retain]
                        [--response-topic RESPONSE_TOPIC]
                        [--username USERNAME] [--password PASSWORD]
                        [--session-expiry-interval SESSION_EXPIRY_INTERVAL]
                        [--message-format {auto,binary,text}]
                        [--cafile CAFILE] [--no-check-hostname]
                        topic [message]
mqttools publish: error: argument --host: expected one argument
usage: mqttools publish [-h] [--host HOST] [--port PORT]
                        [--client-id CLIENT_ID] [--count COUNT] [--size SIZE]
                        [--retain] [--will-topic WILL_TOPIC]
                        [--will-message WILL_MESSAGE] [--will-retain]
                        [--response-topic RESPONSE_TOPIC]
                        [--username USERNAME] [--password PASSWORD]
                        [--session-expiry-interval SESSION_EXPIRY_INTERVAL]
                        [--message-format {auto,binary,text}]
                        [--cafile CAFILE] [--no-check-hostname]
                        topic [message]
mqttools publish: error: argument --host: expected one argument
usage: mqttools publish [-h] [--host HOST] [--port PORT]
                        [--client-id CLIENT_ID] [--count COUNT] [--size SIZE]
                        [--retain] [--will-topic WILL_TOPIC]
                        [--will-message WILL_MESSAGE] [--will-retain]
                        [--response-topic RESPONSE_TOPIC]
                        [--username USERNAME] [--password PASSWORD]
                        [--session-expiry-interval SESSION_EXPIRY_INTERVAL]
                        [--message-format {auto,binary,text}]
                        [--cafile CAFILE] [--no-check-hostname]
                        topic [message]

**Comment by mhzawadi** [comment]
Morning @guba91 

I have just merged in my PHP version, please read the docker hub page and see if you can get the image going.
If you encounter issues, please report back, also if anything needs rewording please let me know

**Comment by guba91** [comment]
Hi! thanks for the fast response!
some new error ;)

root@manage:~# docker run --name foxescloud   -e -TIMEZONE=Europe/Rome   -v /root/foxess-mqtt:/foxess-mqtt/data   mhzawadi/foxess-mqtt
We dont have a timezone, it could UTC
first run will sleep for 5 seconds to allow MQTT to get setup
2023-05-15 11:22:33 - Start of work
PHP Warning:  fopen(data/foxess_data.json): Failed to open stream: No such file or directory in /foxess-mqtt/src/classes/json.php on line 12
PHP Warning:  filesize(): stat failed for data/foxess_data.json in /foxess-mqtt/src/classes/json.php on line 13
PHP Fatal error:  Uncaught TypeError: fread(): Argument #1 ($stream) must be of type resource, bool given in /foxess-mqtt/src/classes/json.php:13
Stack trace:
#0 /foxess-mqtt/src/classes/json.php(13): fread()
#1 /foxess-mqtt/src/controller/foxess_data.php(31): MHorwood\foxess_mqtt\classes\json->load_from_file()
#2 /foxess-mqtt/run.php(7): MHorwood\foxess_mqtt\controller\foxess_data->__construct()
#3 {main}
  thrown in /foxess-mqtt/src/classes/json.php on line 13

**Comment by mhzawadi** [comment]
oh, that needs looking at. will try this evening

**Comment by guba91** [comment]
thanks!
let me know if you need help testing

**Comment by mhzawadi** [comment]
I have good news, I have made some changes to the precess and you should now have a working image (once it builds - https://github.com/mhzawadi/foxess-mqtt/actions/runs/4996791402).

Please use the `mhzawadi/foxess-mqtt:dev-php` image to test, if that works I will merge into main

**Comment by guba91** [comment]
Hi mhzawadi!
Thanks for the update!
now the container starts without error!

`root@manage:~# docker run --name foxescloud   -e -TIMEZONE=Europe/Rome   -v /root/foxess-mqtt:/foxess-mqtt/data   mhzawadi/foxess-mqtt:dev-php
We dont have a timezone, it could UTC
We have all the files we need
first run will sleep for 5 seconds to allow MQTT to get setup
2023-05-17 07:50:38 - Start of work
2023-05-17 07:50:38 - Start of MQTT setup for HA
2023-05-17 07:50:38 - Post to MQTT foxesscloud-generationPower
2023-05-17 07:50:38 - Post to MQTT foxesscloud-generationPower_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-feedinPower
2023-05-17 07:50:38 - Post to MQTT foxesscloud-feedinPower_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-batChargePower
2023-05-17 07:50:38 - Post to MQTT foxesscloud-batChargePower_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-batDischargePower
2023-05-17 07:50:38 - Post to MQTT foxesscloud-batDischargePower_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-gridConsumptionPower
2023-05-17 07:50:38 - Post to MQTT foxesscloud-gridConsumptionPower_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-loadsPower
2023-05-17 07:50:38 - Post to MQTT foxesscloud-loadsPower_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-SoC
2023-05-17 07:50:38 - Post to MQTT foxesscloud-SoC_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-batTemperature
2023-05-17 07:50:38 - Post to MQTT foxesscloud-batTemperature_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-pv1Power
2023-05-17 07:50:38 - Post to MQTT foxesscloud-pv1Power_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-pv2Power
2023-05-17 07:50:38 - Post to MQTT foxesscloud-pv2Power_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-pv3Power
2023-05-17 07:50:38 - Post to MQTT foxesscloud-pv3Power_kwh
2023-05-17 07:50:38 - Post to MQTT foxesscloud-pv4Power
2023-05-17 07:50:38 - Post to MQTT foxesscloud-pv4Power_kwh
2023-05-17 07:50:38 - Setup complete
2023-05-17 07:50:38 - Collect data from the cloud
2023-05-17 07:50:40 - we need to login again
2023-05-17 07:50:40 - start of login
PHP Warning:  Trying to access array offset on value of type null in /foxess-mqtt/src/model/login.php on line 62
2023-05-17 07:50:40 - login error
2023-05-17 07:50:40 - Work complete`

it doesnt like something on the login process :(

**Comment by mhzawadi** [comment]
ok, have got your config.json filled in?

**Comment by guba91** [comment]
oh yess

>  {
>   "foxess_username": "MyUsername",
>   "foxess_password": "Mysupersecretpassword",
>   "device_id": "4hs610c2-therestofmyid",
>   "mqtt_host": "192.168.0.2",
>   "mqtt_port": "1883",
>   "mqtt_user": "mqttusername",
>   "mqtt_pass": "mynotsostrongsuperpassword"
> }

**Comment by mhzawadi** [comment]
you maybe right, I have made a change and the image should be building now

**Comment by guba91** [comment]
i've added echo $return_data['errno']; in that file and the result is:    41807

**Comment by mhzawadi** [comment]
you may have rate limiting, I would wait some time then try again.

side note: I hate the FoxEss Cloud thing, its more wank then a 13 year old on r/boobs

**Comment by mhzawadi** [comment]
have added code to see if the login fails in any way and if so log that and end processing

**Comment by guba91** [comment]
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/92ddb214-0ebf-4757-bc1d-3407555cd823)

well.. shit..

**Comment by mhzawadi** [comment]
see, I would love to find out how we get access to the MQTT endpoint. or a real API

**Comment by guba91** [comment]
i think that there cloud be something wrong (don't mean to be rude) with the login process, because after like 5 min i stopped trying to login with your creation, i can logon on the website. Then i retried with the docker image and [login error], than on the web browser, same error: 40401

can it be that there is something that it doesnt like?

i know it is not a real API and you need to work with the website, and at any moment they can update the backend and broke everything.. it's a mess..

**Comment by mhzawadi** [comment]
ok, i clear have bust something. will have a look this evening.

thanks for all your feedback, it helps get this working 100% of the time 😄

**Comment by guba91** [comment]
no problem!
I wish I could do more but I don't have php skills and docker skills are very basic

**Comment by mhzawadi** [comment]
would you look at that, I have no idea what Im doing 🤦🏼 

so I need to md5 your password, but I have been using an md5 of my password that I have only just spotted.

New image building now, please test?

**Comment by guba91** [comment]
it's workiiiiiiiiiiing!!!!!!!!
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/d9a1d9c1-f83b-49e7-a967-ed6c06acc645)

![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/5e2f57a9-e95f-45f1-ae27-e6ef11c3acfc)


what is foxesscloud/batTemperature_kwh 6.81 ? someone need to measure temperature in kwh??



BTW it looks like you know a lot ;)
![image](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/ce9967c1-c542-44d2-bcda-14a1af21d746)

**Comment by mhzawadi** [comment]
umm, some of that maybe should be temps not kwh 🤦🏼

**Comment by guba91** [comment]
hahahaha
it's fantastic that is working!

if you don't mind i will open other 2 issue to impove this project :)

**Comment by mhzawadi** [comment]
sure, if this is all done then please close and open new issues for improvements.

will merge the changes into main and get the latest image updated

**Comment by guba91** [comment]
thank you!!
