### ISSUE TITLE
Problem with DeviceID

### ISSUE THREAD

**Issue by 19-MRX-98** [mhzawadi/foxess-mqtt#41]
You say that we dont need the DeviceID from Inverter anymore, but my Container say this:

Setting your timezone to Europe/Berlin
We have all the files we need
first run will sleep for 3 seconds to allow MQTT to get setup
This is our timezone: Europe/Berlin
PHP Warning:  Undefined array key "device_id" in /foxess-mqtt/src/model/config.php on line 29
PHP Warning:  fopen(data/error_codes.json): Failed to open stream: No such file or directory in /foxess-mqtt/src/classes/json.php on line 13
PHP Warning:  filesize(): stat failed for data/error_codes.json in /foxess-mqtt/src/classes/json.php on line 14
PHP Fatal error:  Uncaught TypeError: fread(): Argument #1 ($stream) must be of type resource, bool given in /foxess-mqtt/src/classes/json.php:14
Stack trace:
#0 /foxess-mqtt/src/classes/json.php(14): fread()
#1 /foxess-mqtt/src/model/config.php(76): MHorwood\foxess_mqtt\classes\json->load_from_file()
#2 /foxess-mqtt/src/model/device.php(75): MHorwood\foxess_mqtt\model\config->errno()
#3 /foxess-mqtt/src/controller/foxess_data.php(40): MHorwood\foxess_mqtt\model\device->list()
#4 /foxess-mqtt/run.php(8): MHorwood\foxess_mqtt\controller\foxess_data->__construct()
#5 {main}
  thrown in /foxess-mqtt/src/classes/json.php on line 14

**Comment by mhzawadi** [comment]
v0.1.3 has been pushed to the docker hub, please pull that or latest and let me know if your sorted

**Comment by 19-MRX-98** [comment]
I've pulled the latest release, but here is another PHP Error now..

PHP Warning:  fopen(data/error_codes.json): Failed to open stream: No such file or directory in /foxess-mqtt/src/classes/json.php on line 13
PHP Warning:  filesize(): stat failed for data/error_codes.json in /foxess-mqtt/src/classes/json.php on line 14
PHP Fatal error:  Uncaught TypeError: fread(): Argument #1 ($stream) must be of type resource, bool given in /foxess-mqtt/src/classes/json.php:14
Stack trace:
#0 /foxess-mqtt/src/classes/json.php(14): fread()
#1 /foxess-mqtt/src/model/config.php(72): MHorwood\foxess_mqtt\classes\json->load_from_file()
#2 /foxess-mqtt/src/model/device.php(75): MHorwood\foxess_mqtt\model\config->errno()
#3 /foxess-mqtt/src/controller/foxess_data.php(40): MHorwood\foxess_mqtt\model\device->list()
#4 /foxess-mqtt/run.php(8): MHorwood\foxess_mqtt\controller\foxess_data->__construct()
#5 {main}
  thrown in /foxess-mqtt/src/classes/json.php on line 14

It looks like there is a file that is not reachable from the Script

**Comment by mhzawadi** [comment]
oh, will have a look this evening

**Comment by mhzawadi** [comment]
Hey @19-MRX-98 

new dev build on the docker hub, could you test it and if your up and working I will get a new latest build out.

`docker pull mhzawadi/foxess-mqtt:dev-php-0.1.4`

**Comment by 19-MRX-98** [comment]
@mhzawadi

Its running now without any issues! 
Thank you

**Comment by mhzawadi** [comment]
great news, merged the PR and building new latest image
