### ISSUE TITLE
maybe something wrong

### ISSUE THREAD

**Issue by guba91** [mhzawadi/foxess-mqtt#6]
can it be that there is something wrong with the container?
when i try a "docker stop" it take like 30 sec to end it.. sometimes more..
of course it can be a lot f thing, but there is a possibility that something keep the cpu in use while waiting or something?

i first noticed when it failed for the wrong password, cannot close tte attached container with ctrl+c or x.. had to go in another console and kill it or docker stop and wait.. never happen with other docker container so i was thinking that maybe there is somenthing hanging and waiting.. 

or maybe i'm wrong and nothing of this is important LOL  --can be!

**Comment by mhzawadi** [comment]
Hi @guba91 

the slow stopping is the result of how the thing runs, its a shell script that kicks of the PHP. so it will take a bit of time before it fully stops
