### ISSUE TITLE
make Temperature not kW

### ISSUE THREAD

**Issue by mhzawadi** [mhzawadi/foxess-mqtt#8]
turns out Temperature isnt watts

**Comment by mhzawadi** [comment]
hey @guba91,

could you try the `dev-php` image and see if you get all the data?

**Comment by guba91** [comment]
Sadly not at the moment :(
Tomorrow!
Sorry

**Comment by mhzawadi** [comment]
do you think this is enough data from the inverter?
![image](https://github.com/mhzawadi/foxess-mqtt/assets/11944327/f8b4fd12-465d-4956-9587-69702e20258b)

**Comment by guba91** [comment]
> hey @guba91,
> 
> could you try the `dev-php` image and see if you get all the data?
> 
> 

![Screenshot_20230521_135335_JuiceSSH.jpg](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/e6431807-a05b-4096-b431-eea68d449f1a)

![Screenshot_20230521_135325_JuiceSSH.jpg](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/630a5482-309c-4214-887a-45b7b6548051)

Mmm... Look like something isn't ok 🤷‍♂️ in mqtt there is no message from foxess-mqtt

**Comment by mhzawadi** [comment]
the first run using all 63 data points does error, once you have it stored it seems to work fine

**Comment by guba91** [comment]
foxesscloud/SoC 81
foxesscloud/ReactivePower 0
foxesscloud/ReactivePower_kwh 0
foxesscloud/PowerFactor 0
foxesscloud/PowerFactor_kwh 0
foxesscloud/meterPowerT 0
foxesscloud/meterPowerT_kwh 0
foxesscloud/meterPowerS 0
foxesscloud/meterPowerS_kwh 0
foxesscloud/meterPowerR 0
foxesscloud/meterPowerR_kwh 0
foxesscloud/meterPower2 0
foxesscloud/meterPower2_kwh 0
foxesscloud/meterPower 0
foxesscloud/meterPower_kwh 0
foxesscloud/batCurrent 7.6
foxesscloud/batVolt 216.3
foxesscloud/batDischargePower 0
foxesscloud/batDischargePower_kwh 0.98
foxesscloud/batChargePower 1.59
foxesscloud/batChargePower_kwh 0.79
foxesscloud/invBatPower -1.59
foxesscloud/invBatPower_kwh -0.79
foxesscloud/invBatCurrent -7.3
foxesscloud/invBatVolt 215.1
foxesscloud/gridConsumptionPower 0
foxesscloud/gridConsumptionPower_kwh 0
foxesscloud/feedinPower 0
foxesscloud/feedinPower_kwh 0
foxesscloud/generationPower 0.42
foxesscloud/generationPower_kwh 1.04
foxesscloud/loadsPowerT 0
foxesscloud/loadsPowerT_kwh 0
foxesscloud/loadsPowerS 0
foxesscloud/loadsPowerS_kwh 0
foxesscloud/loadsPowerR 0
foxesscloud/loadsPowerR_kwh 0
foxesscloud/loadsPower 0.42
foxesscloud/loadsPower_kwh 1.02
foxesscloud/dspTemperature 0
foxesscloud/batTemperature 33
foxesscloud/chargeTemperature 0
foxesscloud/invTemperation 36.8
foxesscloud/ambientTemperation 40.5
foxesscloud/boostTemperation 0
foxesscloud/TPower 0
foxesscloud/TPower_kwh 0
foxesscloud/TFreq 0
foxesscloud/TFreq_kwh 0
foxesscloud/TVolt 0
foxesscloud/TCurrent 0
foxesscloud/SPower 0
foxesscloud/SPower_kwh 0
foxesscloud/SFreq 0
foxesscloud/SFreq_kwh 0
foxesscloud/SCurrent 0
foxesscloud/SVolt 0
foxesscloud/RPower 0.42
foxesscloud/RPower_kwh 0.18
foxesscloud/RFreq 50
foxesscloud/RFreq_kwh 28
foxesscloud/RVolt 234.2
foxesscloud/RCurrent 1.9
foxesscloud/epsPowerT 0
foxesscloud/epsPowerT_kwh 0
foxesscloud/epsVoltT 0
foxesscloud/epsCurrentT 0
foxesscloud/epsPowerS 0
foxesscloud/epsPowerS_kwh 0
foxesscloud/epsVoltS 0
foxesscloud/epsCurrentS 0
foxesscloud/epsPowerR 0
foxesscloud/epsPowerR_kwh 0
foxesscloud/epsVoltR 0
foxesscloud/epsCurrentR 0
foxesscloud/epsPower 0
foxesscloud/epsPower_kwh 0
foxesscloud/pv4Power 0
foxesscloud/pv4Power_kwh 0
foxesscloud/pv4Volt 0
foxesscloud/pv4Current 0
foxesscloud/pv3Power 0
foxesscloud/pv3Power_kwh 0
foxesscloud/pv3Current 0
foxesscloud/pv3Volt 0
foxesscloud/pv2Power 1.21
foxesscloud/pv2Power_kwh 0.53
foxesscloud/pv2Current 6.4
foxesscloud/pv2Volt 188.9
foxesscloud/pvPower 2.12
foxesscloud/pvPower_kwh 0.86
foxesscloud/pv1Power 0.91
foxesscloud/pv1Power_kwh 0.34
foxesscloud/pv1Current 4.5
foxesscloud/pv1Volt 202

**Comment by guba91** [comment]
what pic do you need?
![Screenshot 2023-05-29 112725](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/a2c655fb-6331-4b2b-b020-f54986f8fde9)
![Screenshot 2023-05-29 112720](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/66538e26-0548-4cb5-849f-80c77caede90)

[foxess.txt](https://github.com/mhzawadi/foxess-mqtt/files/11590483/foxess.txt)

**Comment by mhzawadi** [comment]
thanks, that just what i needed

**Comment by mhzawadi** [comment]
it looks like everything is working, do you see all the data in HA?

**Comment by guba91** [comment]
yes, everything work but i got the warning(s) in the file attached
[KW_kWtxt.txt](https://github.com/mhzawadi/foxess-mqtt/files/11601706/KW_kWtxt.txt)

**Comment by mhzawadi** [comment]
Morning @guba91,

new dev-php image building, could you test it please?

**Comment by guba91** [comment]
> Morning @guba91,
> 
> new dev-php image building, could you test it please?

![Screenshot_20230602_103932_JuiceSSH.jpg](https://github.com/mhzawadi/foxess-mqtt/assets/23064461/23657c93-2299-42db-8652-9bb55416dc8d)

**Comment by guba91** [comment]
Hi @mhzawadi,
now it works but some data are wrong.. the one that i can see at the moment is pvpower, on the web page is ~1500w and in mqtt is 0.29
i'll update you when i have other data

**Comment by mhzawadi** [comment]
how odd, Im still not sure what all the data should be showing.

**Comment by guba91** [comment]
well, it show the data but it is far off.. Soc is correct

**Comment by mhzawadi** [comment]
ok, I have had a look and the `pvpower` in mqtt is the total from all 4 of the solar inputs. I think.

Also where on the site did you see it as I now cant find it 😢

**Comment by mhzawadi** [comment]
so there is a bug somewhere, cuz I didnt use 70KWh in an hour
![image](https://github.com/mhzawadi/foxess-mqtt/assets/11944327/21fac87f-bb4f-4f32-a8b2-7eb7400f3ed0)

**Comment by guba91** [comment]
hahaha hope you don't!

**Comment by guba91** [comment]
> here on the sit



> Also where on the site did you see it as I now cant find it 😢

mmm.. pvpower isn't the solar generated power? like "how many kw is the solar generating"? like volt multiplied amps per channel?
